package com.doubleclue.dcem.skills.exceptions;

public enum SkillsErrorCodes {
	CANNOT_CHANGE_SKILL_ROOT,
	CANNOT_DELETE_SKILL_ROOT,
	CANNOT_EDIT_NON_OBTAINABLE_SKILL, 
	CANNOT_ADD_NON_APPROVED_SKILL,
	PARENT_MUST_BE_APPROVED;
	

}
